name: Upload Python Package

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  deploy:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

      # This permission allows writing releases
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.9.0"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install Python
        run: uv python install ${{ matrix.python-version }}

      - name: Build
        run: uv build

      - name: Test
        run: uv run pytest

      - name: Publish
        run: uv publish

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
