name: Upload Python Package

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  deploy:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

      # This permission allows writing releases
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Python 3.12
        run: uv python install 3.12

      - name: Build
        run: uv build

      - name: Test
        run: uv run pytest

      - name: Publish
        run: uv publish

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
